#!/usr/bin/env python3
"""Generate the half-block truecolor crab sprite used by the interactive desk pet.

Reads assets/character.png, autocrops the alpha bounding box, downsamples to a
small cell width, and emits two "bob" frames (the second shifted down one
sub-pixel) so the pet has a gentle idle animation. Each frame is one terminal
line per two pixel rows using U+2580 "▀" / U+2584 "▄" with 24-bit ANSI colors.

Usage:
    python scripts/generate-pet-sprite.py

Requires Pillow (PIL). Output is checked in as a generated TS module so the CLI
needs no runtime image decode or bundled asset. Non-truecolor terminals use the
ASCII fallback crab in pet.ts instead.
"""

from __future__ import annotations

import os

from PIL import Image

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SOURCE = os.path.join(REPO_ROOT, "assets", "character.png")
OUTPUT = os.path.join(
    REPO_ROOT,
    "packages",
    "coding-agent",
    "src",
    "modes",
    "components",
    "pet-sprite.generated.ts",
)
COLS = 10
ALPHA_OPAQUE = 100
RESET = "\x1b[0m"


def load_cropped(path: str, pad: int = 1) -> Image.Image:
    img = Image.open(path).convert("RGBA")
    bbox = img.split()[3].getbbox()
    if bbox:
        left, top, right, bottom = bbox
        img = img.crop(
            (
                max(0, left - pad),
                max(0, top - pad),
                min(img.width, right + pad),
                min(img.height, bottom + pad),
            )
        )
    return img


def shift_down(img: Image.Image, px: int) -> Image.Image:
    if px <= 0:
        return img
    canvas = Image.new("RGBA", img.size, (0, 0, 0, 0))
    canvas.paste(img, (0, px))
    return canvas


def rasterize(img: Image.Image, cols: int) -> list[str]:
    width, height = img.size
    rows = max(1, round(cols * (height / width) / 2))
    small = img.resize((cols, rows * 2), Image.LANCZOS)
    px = small.load()
    lines: list[str] = []
    for r in range(rows):
        line = ""
        for c in range(cols):
            tr, tg, tb, ta = px[c, r * 2]
            br, bg, bb, ba = px[c, r * 2 + 1]
            top = ta >= ALPHA_OPAQUE
            bot = ba >= ALPHA_OPAQUE
            if top and bot:
                line += f"\x1b[38;2;{tr};{tg};{tb};48;2;{br};{bg};{bb}m\u2580{RESET}"
            elif top:
                line += f"\x1b[38;2;{tr};{tg};{tb}m\u2580{RESET}"
            elif bot:
                line += f"\x1b[38;2;{br};{bg};{bb}m\u2584{RESET}"
            else:
                line += " "
        lines.append(line)
    return lines


def ts_escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace("\x1b", "\\u001b").replace('"', '\\"')


def frame_ts(frame: list[str]) -> str:
    return "\t[\n" + ",\n".join('\t\t"' + ts_escape(line) + '"' for line in frame) + ",\n\t]"


def main() -> None:
    img = load_cropped(SOURCE)
    frame0 = rasterize(img, COLS)
    height = len(frame0)
    frame1 = rasterize(shift_down(img, round(img.height / (height * 2))), COLS)
    blank = " " * COLS
    frame0 = (frame0 + [blank] * height)[:height]
    frame1 = (frame1 + [blank] * height)[:height]
    body = ",\n".join(frame_ts(f) for f in (frame0, frame1))
    header = (
        "// Auto-generated by scripts/generate-pet-sprite.py from assets/character.png - DO NOT EDIT.\n"
        f"// Half-block (\u2580/\u2584) truecolor crab pet, {COLS} cells wide, 2 bob frames.\n"
        "// Regenerate: python scripts/generate-pet-sprite.py\n\n"
    )
    out = header
    out += f"export const PET_SPRITE_WIDTH = {COLS};\n"
    out += f"export const PET_SPRITE_HEIGHT = {height};\n\n"
    out += "export const PET_SPRITE_FRAMES: readonly (readonly string[])[] = [\n" + body + ",\n];\n"
    with open(OUTPUT, "w", encoding="utf-8") as fh:
        fh.write(out)
    print(f"wrote {OUTPUT} (2 frames, {COLS}x{height})")


if __name__ == "__main__":
    main()
